server:
  port: 8082
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-local
      - security-local
      - elasticsearch-local

logging:
  level:
    root: DEBUG