server:
  port: 8082
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-prod
      - security-prod
      - elasticsearch-prod
      - rabbit-prod
      - cookie-prod
      - log-prod
