server:
  port: 8082
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-local
      - security-local
      - elasticsearch-local
      - cookie-local


logging:
  level:
    root: DEBUG