server:
  port: 8081
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-local
      - flyway-member
      - security-local
      - cookie-local

logging:
  level:
    root: DEBUG