server:
  port: 8081
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-prod
      - flyway-member
      - security-prod
      - cookie-prod
      - rabbit-prod
      - log-prod
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
