server:
  port: 8081
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql
      - flyway-member
      - security
      - cookie
      - rabbit
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
