server:
  port: 8081
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-local
      - flyway-member
      - security-local
      - cookie-local
  redis:
    host: localhost
    port: 16379
    password:

logging:
  level:
    root: DEBUG