server:
  port: 8083
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-local
      - security-local
      - redis-local
      - cookie-local
      - rabbit-local
      - rabbitmq-local
      - log-local

logging:
  level:
    root: DEBUG