spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
              enable: true
          EnableSSL:
                enable: true