spring:
  mail:
    protocol: smtp
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
            enable: true
          EnableSSL:
            enable: true