server:
  port: 8084
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - mysql-dev
      - flyway-notification
      - security-dev
      - mail-dev
      - rabbit-dev
      - cookie-dev
